-- MySQL Script generated by MySQL Workbench
-- Tue May 10 21:03:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Place` VARCHAR(45) NOT NULL,
  `Ph_No` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Cus_Ph_No_UNIQUE` (`Ph_No` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`House`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`House` (
  `ID` INT NOT NULL,
  `Type_Of_House` VARCHAR(45) NOT NULL,
  `Place` VARCHAR(45) NOT NULL,
  `Type_Of_Contractor` VARCHAR(45) NOT NULL,
  `Agreement` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `Request_status for quote` VARCHAR(45) NOT NULL,
  `Customer_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Agreement_UNIQUE` (`Agreement` ASC) VISIBLE,
  INDEX `fk_House_Customer1_idx` (`Customer_ID` ASC) VISIBLE,
  CONSTRAINT `fk_House_Customer1`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `mydb`.`Customer` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contractor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contractor` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Place` VARCHAR(45) NOT NULL,
  `Ph_No` VARCHAR(45) NOT NULL,
  `Availability` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Cont_Ph_No_UNIQUE` (`Ph_No` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Worker` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Availability` VARCHAR(45) NOT NULL,
  `Ph_No` VARCHAR(45) NOT NULL,
  `Place` VARCHAR(45) NOT NULL,
  `wage` INT NOT NULL,
  `Type_of_worker` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Wor_Ph_No_UNIQUE` (`Ph_No` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Materials` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Qty` VARCHAR(45) NOT NULL,
  `Place` VARCHAR(45) NOT NULL,
  `Price` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`House_has_Materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`House_has_Materials` (
  `House_ID` INT NOT NULL,
  `Materials_ID` INT NOT NULL,
  `Mat_Qty_taken` VARCHAR(45) NOT NULL,
  `cost_of_material(overall)` INT NOT NULL,
  `order_date` DATETIME NOT NULL,
  INDEX `fk_House_has_Materials_Materials1_idx` (`Materials_ID` ASC) VISIBLE,
  INDEX `fk_House_has_Materials_House1_idx` (`House_ID` ASC) VISIBLE,
  CONSTRAINT `fk_House_has_Materials_House1`
    FOREIGN KEY (`House_ID`)
    REFERENCES `mydb`.`House` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_House_has_Materials_Materials1`
    FOREIGN KEY (`Materials_ID`)
    REFERENCES `mydb`.`Materials` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`House_has_Worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`House_has_Worker` (
  `House_ID` INT NOT NULL,
  `Worker_ID` INT NOT NULL,
  `Date` VARCHAR(45) NOT NULL,
  `Amount spent` INT NULL,
  INDEX `fk_House_has_Worker_Worker1_idx` (`Worker_ID` ASC) VISIBLE,
  INDEX `fk_House_has_Worker_House1_idx` (`House_ID` ASC) VISIBLE,
  INDEX `fk_` () VISIBLE,
  UNIQUE INDEX `Date_UNIQUE` (`Date` ASC) VISIBLE,
  PRIMARY KEY (`House_ID`, `Worker_ID`, `Date`),
  CONSTRAINT `fk_House_has_Worker_House1`
    FOREIGN KEY (`House_ID`)
    REFERENCES `mydb`.`House` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_House_has_Worker_Worker1`
    FOREIGN KEY (`Worker_ID`)
    REFERENCES `mydb`.`Worker` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Credentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Credentials` (
  `Login_id` INT NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `User_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Login_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`House_has_Contractor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`House_has_Contractor` (
  `House_ID` INT NOT NULL,
  `Contractor_ID` INT NOT NULL,
  `quote_prize` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`House_ID`, `Contractor_ID`),
  INDEX `fk_House_has_Contractor_Contractor1_idx` (`Contractor_ID` ASC) VISIBLE,
  INDEX `fk_House_has_Contractor_House1_idx` (`House_ID` ASC) VISIBLE,
  CONSTRAINT `fk_House_has_Contractor_House1`
    FOREIGN KEY (`House_ID`)
    REFERENCES `mydb`.`House` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_House_has_Contractor_Contractor1`
    FOREIGN KEY (`Contractor_ID`)
    REFERENCES `mydb`.`Contractor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`workers_needed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`workers_needed` (
  `type_of_worker` VARCHAR(45) NOT NULL,
  `Date` DATETIME NOT NULL,
  `Number_req` INT NOT NULL,
  `House_ID` INT NOT NULL,
  CONSTRAINT `fk_workers_needed_House1`
    FOREIGN KEY (`House_ID`)
    REFERENCES `mydb`.`House` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
